# Generated by Django 4.2.3 on 2023-07-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('created_at_dt', models.DateTimeField()),
            ],
        ),
    ]
